### PR TITLE
added support for multiple actions per request

### PR DESCRIPTION
**Pull request by geovanisouza92**
I think that this could be useful for manipulating the storage.

### CODE REVIEW

**Comment by jvanbruegge** [comment]
Do you have a use case for the new methods in Cyclejs?

**Comment by geovanisouza92** [comment]
I'm trying to persist the state of a component for when the app is reloaded.

Sometimes I need to remove an item or clear it entirely.

I think that sometimes could make more sense "ask for removal/cleaning" instead of "set it to null/empty".

**Comment by jvanbruegge** [comment]
The problem is, that all writes are fed back to the application, so the code would have to either filter the remove reqeusts in the driver, or this would be a breaking change, as not every event fed to an application is a new value.

**Comment by geovanisouza92** [comment]
Yes, didn't noticed that

**Comment by geovanisouza92** [comment]
Do you think that just filtering out 'clear' actions is sufficient?

**Comment by jvanbruegge** [comment]
Maybe we dont have to filter them at all as remove actions are not possible in a program not using them. No breaking change then.
Do you think the new events are useful as source? (so basicly is your workflow event-->storage-->dom or event-->storage&dom?)

**Comment by geovanisouza92** [comment]
Ok them,

My workflow is kind of `event -> storage & state -> dom`

**Comment by jvanbruegge** [comment]
yeah, i thought so, I would fillter them both. At least by default. You can add an optional option to the driver to disable filtering if you like

**Pull request closed without merging**
